version: '3.8'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eridu_test_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
