@port = {{$dotenv PORT}}
@url = http://localhost:{{port}}
@user_email = {{$dotenv TEST_USER_EMAIL}}
@user_password = {{$dotenv TEST_USER_PASSWORD}}
@reset_token=
@user_new_password =
@user_uid = 
@business_uid = biz_m_sDy9e9e_cf1g2ikllIg
@business_name = 
@team_uid = 
@team_name = 
@role_uid = role_8XqpitKx5XK5NXXsoIG8A
@role_name = erify_1_manager

// user signup
// @name signup
POST {{url}}/auth/signup
Accept: application/json
Content-Type: application/json

{
  "email": "{{user_email}}",
  "password": "{{user_password}}"
}

###
// user login
// @name login
POST {{url}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{user_email}}",
  "password": "{{user_password}}"
}
###
@access_token = {{login.response.body.accessToken}}
@refresh_token_cookie = {{login.response.headers.Set-Cookie}}

###
// user logout
// @name logout
POST {{url}}/auth/logout
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json
Cookie: {{refresh_token_cookie}}

###
// refresh user token
// @name refreshToken
POST {{url}}/auth/refresh
Authorization: Bearer {{access_token}}
Accept: application/
Content-Type: application/json
Cookie: {{refresh_token_cookie}}

###
@access_token = {{refreshToken.response.body.accessToken}}

### 
// change user password
PUT {{url}}/auth/change-password
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "email": "{{user_email}}",
  "oldPassword": "{{user_password}}",
  "newPassword": "{{user_new_password}}",
  "confirmNewPassword": "{{user_new_password}}"
}

###
// reset user password
POST {{url}}/auth/reset-password
Accept: application/json
Content-Type: application/json

{
  "password": "{{user_password}}",
  "confirmPassword": "{{user_password}}",
  "token": "{{reset_token}}"
}

###
// get user info
// @name get_user_info
GET {{url}}/auth/me
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// create reset token by admin
// @name create_reset_token_by_admin
POST {{url}}/admin/users/{{user_uid}}/reset-token
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// search business by admin
// @name get_businesses
GET {{url}}/admin/businesses
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// search a business by UID by admin
// @name get_business_by_uid
GET {{url}}/admin/businesses/{{business_uid}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// search a business by UID by admin
// @name update_business_by_admin
PUT {{url}}/admin/businesses/{{business_uid}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "name": "erify_1"
}

###
// create a business by admin
// @name create_business_by_admin
POST {{url}}/admin/businesses
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{ "name": "{{business_name}}" }

###
// delete a business by admin
// @name delete_business_by_admin
DELETE {{url}}/admin/businesses/{{business_uid}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// search teams by admin
// @name search_teams_by_admin
GET {{url}}/admin/teams
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// create a team by admin
// @name create_team_by_admin
POST {{url}}/admin/teams
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "name": "{{team_name}}",
  "business_id": "{{business_uid}}"
}

###
// search memberships by admin
// @name search_memberships_by_admin
GET {{url}}/admin/memberships
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

### 
// create a membership by admin
// @name create_membership_by_admin
POST {{url}}/admin/memberships
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "user_id": "{{user_uid}}",
  "team_id": "{{team_uid}}",
  "role_id": "{{role_uid}}"
}

###
// search roles by admin
// @name search_roles_by_admin
GET {{url}}/admin/roles
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// create a role by admin
// @name create_role_by_admin
POST {{url}}/admin/roles
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "name": "{{role_name}}",
  "business_id": "{{business_uid}}"
}

###
// search a role by UID by admin
// @name get_role_by_uid
GET {{url}}/admin/roles/{{role_uid}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

###
// update a role by admin
// @name update_role_by_admin
PUT {{url}}/admin/roles/{{role_uid}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "name": "{{role_name}}"
}
